name: codecov
on: [push, pull_request]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch
        uses: actions/checkout@master
      - name: Test
        run: |
          make test
          sudo apt-get install -y gcovr
          gcovr --exclude='tests/*' --json cov.json
          curl -Os https://uploader.codecov.io/latest/linux/codecov && chmod +x codecov 
          ./codecov -f cov.json
      - name: Upload
        uses: codecov/codecov-action@v2
        with:
          files: cov.json
