name: Build and Test
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch
        uses: actions/checkout@master
      - name: Test
        run: |
          make test
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch
        uses: actions/checkout@master
      - name: Install stuff
        run: |
          sudo apt-get install -y gcovr
          curl -Os https://uploader.codecov.io/latest/linux/codecov && chmod +x codecov 
      - name: Test
        run: |
          make test
      - name: Generate coverage statistics
        run: |
          gcovr --exclude='tests/*' -x cov.xml > cov.xml
      - name: Upload 
        run: |
          ./codecov -f cov.xml
