name: Build and Test
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch
        uses: actions/checkout@master
      - name: Test
        run: |
          make test
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch
        uses: actions/checkout@master
      - name: Install stuff
        run: |
          sudo apt-get install -y gcovr
          curl -Os https://uploader.codecov.io/latest/linux/codecov && chmod +x codecov 
      - name: Test
        run: |
          make test COV=1
      - name: Generate coverage statistics
        run: |
          gcovr -x cov.xml 
          # This is for debugging
          gcovr 
      - name: Upload 
        run: |
          ./codecov -f cov.xml
